export const servicesAbi = [
  {
    type: "event",
    name: "PaymentReleased",
    inputs: [
      { name: "escrowId", type: "bytes32", indexed: true },
      { name: "to", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "stage", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "WithdrawalQueued",
    inputs: [
      { name: "account", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "WithdrawalExecuted",
    inputs: [
      { name: "account", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
  {
    type: "function",
    name: "getEscrowState",
    stateMutability: "view",
    inputs: [{ name: "escrowId", type: "bytes32" }],
    outputs: [
      { name: "buyer", type: "address" },
      { name: "seller", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "escrowAmount", type: "uint256" },
      { name: "releasedToSeller", type: "uint256" },
      { name: "numMilestones", type: "uint8" },
      { name: "completedMilestones", type: "uint8" },
      { name: "depositReleased", type: "bool" },
      { name: "halfwayReleased", type: "bool" },
      { name: "completionReleased", type: "bool" },
      { name: "satisfactionReleased", type: "bool" },
      { name: "midwayReviewed", type: "bool" },
      { name: "finalReviewed", type: "bool" },
      { name: "disputed", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "escrows",
    stateMutability: "view",
    inputs: [{ name: "escrowId", type: "bytes32" }],
    outputs: [
      { name: "buyer", type: "address" },
      { name: "seller", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "escrowAmount", type: "uint256" },
      { name: "releasedToSeller", type: "uint256" },
      { name: "createdAt", type: "uint256" },
      { name: "numMilestones", type: "uint8" },
      { name: "completedMilestones", type: "uint8" },
      { name: "depositReleased", type: "bool" },
      { name: "halfwayReleased", type: "bool" },
      { name: "completionReleased", type: "bool" },
      { name: "satisfactionReleased", type: "bool" },
      { name: "disputed", type: "bool" },
      { name: "disputeAmount", type: "uint256" },
      { name: "midwayRespect", type: "uint8" },
      { name: "midwayComm", type: "uint8" },
      { name: "midwayTimeliness", type: "uint8" },
      { name: "midwayQuality", type: "uint8" },
      { name: "midwayReviewed", type: "bool" },
      { name: "finalRespect", type: "uint8" },
      { name: "finalComm", type: "uint8" },
      { name: "finalTimeliness", type: "uint8" },
      { name: "finalQuality", type: "uint8" },
      { name: "finalReviewed", type: "bool" },
      { name: "exemplaryNoted", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "pendingWithdrawals",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  { type: "function", name: "releaseDeposit", stateMutability: "nonpayable", inputs: [{ name: "escrowId", type: "bytes32" }], outputs: [] },
  { type: "function", name: "completeMilestone", stateMutability: "nonpayable", inputs: [{ name: "escrowId", type: "bytes32" }, { name: "index", type: "uint256" }], outputs: [] },
  { type: "function", name: "submitMidwayReview", stateMutability: "nonpayable", inputs: [{ name: "escrowId", type: "bytes32" }, { name: "respect", type: "uint8" }, { name: "comm", type: "uint8" }, { name: "timeliness", type: "uint8" }, { name: "quality", type: "uint8" }], outputs: [] },
  { type: "function", name: "releaseCompletion", stateMutability: "nonpayable", inputs: [{ name: "escrowId", type: "bytes32" }], outputs: [] },
  { type: "function", name: "submitFinalReview", stateMutability: "payable", inputs: [{ name: "escrowId", type: "bytes32" }, { name: "respect", type: "uint8" }, { name: "comm", type: "uint8" }, { name: "timeliness", type: "uint8" }, { name: "quality", type: "uint8" }], outputs: [] },
  { type: "function", name: "withdraw", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "openDispute", stateMutability: "nonpayable", inputs: [{ name: "escrowId", type: "bytes32" }, { name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "resolveDispute", stateMutability: "payable", inputs: [{ name: "escrowId", type: "bytes32" }, { name: "toBuyer", type: "uint256" }, { name: "toSeller", type: "uint256" }], outputs: [] },
  { type: "function", name: "cancelExpiredEscrow", stateMutability: "nonpayable", inputs: [{ name: "escrowId", type: "bytes32" }], outputs: [] },
];

