export const categories = [
  {
    id: 1,
    name: "Shopping Mall",
    image: "/new/shopping mall.jpg",
    // extraclass: "w-[100%] object-cover h-[165%]",
    link: "/shoppingMall/all",
  },
  {
    id: 2,
    name: "Shop by Store concierge game",
    image: "/new/shp.jpg",
    // extraclass: "w-[100%] object-cover h-[165%]",
    link: "/home",
  },
  {
    id: 3,
    name: "My Store",
    image: "/new/mystore2.jpg",
    // extraclass: "w-[100%] object-cover h-[165%]",
    link: "/pinksurfing.com",
  },
];
export const subCategories = [
  {
    id: "1",
    name: "Trading Cards",
    image: "/new/trading_cards1.jpg",
    category: "trading-cards",
    extraclass: "object-cover",
    link: "/home",
  },
  {
    id: "2",
    name: "Beauty/Makeup",
    category: "beauty-makeup",
    image: "/new/beauty_makeup.jpg",
    extraclass: "object-cover",
    link: "/home",
  },
  {
    id: "3",
    name: "Toys",
    category: "toy",
    image: "/new/toys.jpg",
    extraclass: "w-full h-full",
    link: "/home",
  },
  {
    id: "4",
    name: "Electronics",
    category: "electronics",
    image: "/new/electronics.jpg",
    extraclass: "object-cover",
    link: "/home",
  },
  {
    id: "20",
    name: "Residential Real Estate",
    category: "residential-real-estate",
    image: "/new/real_estate3.jpg",
    extraclass: "object-cover",
    link: "/home",
  },
  {
    id: "21",
    name: "Commercial Real Estate",
    category: "commercial-real-estate",
    image: "/new/real_estate3.jpg",
    extraclass: "object-cover",
    link: "/home",
  },
  {
    id: "5",
    name: "Jobs/Gigs",
    category: "jobs",
    image: "/new/jobs.jpg",
    extraclass: "object-cover",
    link: "/home",
  },
  {
    id: "6",
    name: "Perfumes",
    category: "perfumes",
    image2: "/new/beauty.jpg",
    extraclass: "object-cover",
    image : '/new/perfume.jpg',
    link: "/home",
  },
  {
    id: "9",
    name: " AI Agents 4 Sale",
    category: "AI Agents",
    image: "/new/ai_agents.jpg",
    extraclass: "",
    link: "/home",
  },
  {
    id: "11",
    name: "Entertainment",
    category: "entertainment",
    image: "/new/entertainment1.jpg",
    extraclass: "",
    link: "/home",
  },
  {
    id: "12",
    name: "Cars and Trucks",
    category: "cars-trucks",
    image: "/new/cars_and_trucks.jpg",
    extraclass: "",
    link: "/home",
  },
  {
    id: "13",
    name: "Building Materials",
    category: "building-materials",
    image: "/new/building_materials.jpg",
    extraclass: "",
    link: "/home",
  },
  {
    id: "14",
    name: "Video Games",
    category: "video-games",
    image: "/new/viedo_games.jpg",
    extraclass: "w-full h-full",
    link: "/home",
  },
  {
    id: "15",
    name: "Hotels",
    category: "hotels",
    image: "/new/hotel.jpg",
    extraclass: "",
    link: "/home",
  },
  {
    id: "16",
    name: "Business For Sale",
    category: "business-for-sale",
    image: "/new/business for sale.jpg",
    extraclass: "",
    link: "/home",
  },
  {
    id: "17",
    name: "Computer Parts",
    category: "computer-parts",
    image: "/new/computer_parts.jpg",
    extraclass: "",
    link: "/home",
  },
  // {
  //   id: "18",
  //   name: "Channels 4 Sale",
  //   category: "Channels for Sale",
  //   image: "/new/channels.jpg",
  //   extraclass: "",
  //   link: "/home",
  // },
];
